eureka:
  client:
    preferIpAddress: true
    ip-address: http://ec2-3-84-219-98.compute-1.amazonaws.com/
    prefer-same-zone-eureka: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-84-219-98.compute-1.amazonaws.com:8761/eureka/
